### ISSUE TITLE
If statement not working

### ISSUE THREAD

**Issue by The127** [The127/MScript#22]
trouble writing an if-statement:

//---------------------------------
def db as base;

fn main (){
var x;
loop {
x=calc(5);
write x into base.Setting;
yield;
}
}

fn calc(b) {
if(b<=5){b=b+1;}
return b;
}
//---------------------------------

Exception in thread "main" com.github.The127.MScript.MScriptCompilationException: Could not find source label: {source::goto::__lessOrEqual}
at com.github.The127.MScript.LabelResolver.lambda$resolveLabels$0(LabelResolver.java:32)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at com.github.The127.MScript.LabelResolver.resolveLabels(LabelResolver.java:26)
at com.github.The127.MScript.MScriptCompiler.main(MScriptCompiler.java:27)

**Comment by The127** [comment]
The problem is that the runtime is not being told that it should generate code for the 'lessOrEqual'-Operation.

Debug Output:

java -jar MScript.jar res/test_if.ms -d
Runtime: enabling 'function call'.
Runtime: enabling condition evaluation.
Runtime: enabling 'addition'.
Runtime: enabling 'return'.
BEGIN DEBUG Runtime-Output
isAddUsed: true
isFunctionCalled: true
isConditionEvaluated: true
isRetUsed: true
END DEBUG Runtime-Output
Exception in thread "main" com.github.The127.MScript.MScriptCompilationException: Could not find source label: {source::goto::__lessOrEqual}
        at com.github.The127.MScript.LabelResolver.lambda$resolveLabels$0(LabelResolver.java:32)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.github.The127.MScript.LabelResolver.resolveLabels(LabelResolver.java:26)
        at com.github.The127.MScript.MScriptCompiler.main(MScriptCompiler.java:37)

**Comment by The127** [comment]
There was also a missing goto-label on the 'condition'-runtime part.
